prometheus:
  datadir: /var/lib/prometheus
  config_file: /etc/prometheus/prometheus.yml
  external_url: http://127.0.0.1:9090/
  retention: 15d
  web_console_templates: /etc/prometheus/consoles
  web_console_libraries: /etc/prometheus/console_libraries
  alertmanager_url: http://127.0.0.1:9093
  rule_files:
    - "rules.yml"
    - "rules.d/*.yml"
    - "rules.d/*.yaml"
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  config:
    default_receiver: default
    group_by: "[ instance, alertname, summary ]"
    group_wait: 5s
    group_interval: 1m
    repeat_interval: 5h
  scrape_configs:
    prometheus:
      targets:
        - localhost:9090 
